# Linkus Example Configuration

# Application settings
app:
  title: My Dashboard
  theme: light

# Services list (links, ping checks, plugins)
services:
  # Simple Link Example
  - name: Search Engine
    type: http_check
    icon: search-web
    url: https://duckduckgo.com
    category: general
    description: Privacy-focused search
    # groups:
    #   - admin
    # user:
    #   - admin

  # Ping Check Example
  - name: Local Router
    type: http_check
    icon: router-wireless
    url: http://192.168.1.1
    category: network
    description: Check router status
    ping_interval: 60

  # Plugin Example (Clock)
  - name: Clock
    type: plugin
    plugin: clock
    icon: clock-outline
    category: general
    description: Displays the current time

# Categories to group services
categories:
  - id: general
    name: General
    icon: view-dashboard
  - id: network
    name: Network
    icon: lan
# Test Headers (for local development without reverse proxy auth)
# Uncomment and set these if running locally and need to simulate authenticated user
# testHeader:
#   Remote-User: bob
#   Remote-Groups: admin,dev,media
#   Remote-Name: John Smith
#   Remote-Email: jsmith@example.com
